---
- name: Build and deploy Dex with TLS support
  hosts: localhost
  gather_facts: false
  vars_files:
      - ../Vars/dex-vars.yml

  vars:
      tls_cert_dir: /root/certs
      dex_tls_cert_path: "{{ tls_cert_dir }}/tls.crt"
      dex_tls_key_path: "{{ tls_cert_dir }}/tls.key"
      dex_tls_ip: "{{ dex_issuer | regex_replace('https://', '') | regex_replace(':.*$', '') }}"

  tasks:
      - name: Ensure certs directory exists
        file:
            path: "{{ tls_cert_dir }}"
            state: directory
            mode: "0700"

      - name: Apply namespace
        command: kubectl apply -f ../Manifest/dex-namespace.yml

      - name: Generate TLS certificates for Dex
        command: >
            openssl req -x509 -newkey rsa:4096
            -keyout {{ dex_tls_key_path }}
            -out {{ dex_tls_cert_path }}
            -days 365 -nodes
            -subj "/CN={{ dex_tls_ip }}"
            -addext "subjectAltName=IP:{{ dex_tls_ip }}"
        args:
            creates: "{{ dex_tls_cert_path }}"

      - name: Check if dex-tls secret already exists
        command: kubectl -n {{ dex_namespace }} get secret {{ dex_tls_secret_name }}
        register: dex_tls_secret_check
        ignore_errors: true

      - name: Create dex-tls secret in Kubernetes (only if it doesn't exist)
        command: >
            kubectl -n {{ dex_namespace }} create secret tls {{ dex_tls_secret_name }}
            --cert={{ dex_tls_cert_path }} --key={{ dex_tls_key_path }}
        when: dex_tls_secret_check.rc != 0

      - name: Apply service account
        command: kubectl apply -f ../Manifest/dex-serviceaccount.yml

      - name: Apply RBAC
        command: kubectl apply -f ../Manifest/dex-rbac.yml

      - name: Apply ConfigMap
        command: kubectl apply -f ../Manifest/dex-configmap.yml

      - name: Apply Deployment
        command: kubectl apply -f ../Manifest/dex-deployment.yml

      - name: Apply Service
        command: kubectl apply -f ../Manifest/dex-service.yml
